sudo: required
services:
  - docker

before_install:
  - docker build -t dejansukalo/react_app -f Dockerfile.dev .

script:
 - docker run -e CI=true dejansukalo/react_app npm run test -- --coverage 

after_success:
  - docker build -t dejansukalo/react_app ./sample

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push dejansukalo/react_app

