sudo: required
services:
  - docker

before_install:
  - docker build -t dejansukalo/react_app -f Dockerfile.dev .

script:
 - docker run -e CI=true dejansukalo/react_app npm run test -- --coverage 

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-eu-central-1-927112977430"
  bucket_path: "docker"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY 
  secret_access_key: "$AWS_SECRET_KEY"

